package sqlite_test

import (
	"context"
	"database/sql"
	"fmt"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	"vacaytracker-api/internal/domain"
	"vacaytracker-api/internal/repository/sqlite"
	"vacaytracker-api/internal/testutil"
)

// ---------------------------------------------------------------------------
// 1. Create & GetByID
// ---------------------------------------------------------------------------

func TestUserCreate_AndGetByID(t *testing.T) {
	db := testutil.SetupTestDB(t)
	repo := sqlite.NewUserRepository(db)
	ctx := context.Background()

	startDate := "2024-01-15"
	user := &domain.User{
		ID:              "test-user-1",
		Email:           "alice@example.com",
		PasswordHash:    "hashed-password-abc",
		Name:            "Alice Wonderland",
		Role:            domain.RoleEmployee,
		VacationBalance: 25,
		StartDate:       &startDate,
		EmailPreferences: domain.EmailPreferences{
			VacationUpdates:   true,
			WeeklyDigest:      false,
			TeamNotifications: true,
		},
	}

	err := repo.Create(ctx, user)
	require.NoError(t, err)

	fetched, err := repo.GetByID(ctx, "test-user-1")
	require.NoError(t, err)
	require.NotNil(t, fetched)

	assert.Equal(t, "test-user-1", fetched.ID)
	assert.Equal(t, "alice@example.com", fetched.Email)
	assert.Equal(t, "hashed-password-abc", fetched.PasswordHash)
	assert.Equal(t, "Alice Wonderland", fetched.Name)
	assert.Equal(t, domain.RoleEmployee, fetched.Role)
	assert.Equal(t, 25, fetched.VacationBalance)
	require.NotNil(t, fetched.StartDate)
	assert.Equal(t, "2024-01-15", *fetched.StartDate)
	assert.True(t, fetched.EmailPreferences.VacationUpdates)
	assert.False(t, fetched.EmailPreferences.WeeklyDigest)
	assert.True(t, fetched.EmailPreferences.TeamNotifications)
	assert.False(t, fetched.CreatedAt.IsZero())
	assert.False(t, fetched.UpdatedAt.IsZero())
}

// ---------------------------------------------------------------------------
// 2. Create with auto-generated ID
// ---------------------------------------------------------------------------

func TestUserCreate_AutoGeneratedID(t *testing.T) {
	db := testutil.SetupTestDB(t)
	repo := sqlite.NewUserRepository(db)
	ctx := context.Background()

	user := &domain.User{
		ID:               "", // empty — should be auto-generated
		Email:            "auto-id@example.com",
		PasswordHash:     "hash123",
		Name:             "Auto User",
		Role:             domain.RoleEmployee,
		VacationBalance:  20,
		EmailPreferences: domain.DefaultEmailPreferences(),
	}

	err := repo.Create(ctx, user)
	require.NoError(t, err)

	// The repository mutates user.ID in place
	assert.NotEmpty(t, user.ID)
	assert.Contains(t, user.ID, "usr_")

	// Verify it can be fetched back
	fetched, err := repo.GetByID(ctx, user.ID)
	require.NoError(t, err)
	require.NotNil(t, fetched)
	assert.Equal(t, "Auto User", fetched.Name)
}

// ---------------------------------------------------------------------------
// 3. Create duplicate email
// ---------------------------------------------------------------------------

func TestUserCreate_DuplicateEmail(t *testing.T) {
	db := testutil.SetupTestDB(t)
	repo := sqlite.NewUserRepository(db)
	ctx := context.Background()

	user1 := &domain.User{
		ID:               "user-dup-1",
		Email:            "same@example.com",
		PasswordHash:     "hash",
		Name:             "First User",
		Role:             domain.RoleEmployee,
		VacationBalance:  25,
		EmailPreferences: domain.DefaultEmailPreferences(),
	}
	err := repo.Create(ctx, user1)
	require.NoError(t, err)

	user2 := &domain.User{
		ID:               "user-dup-2",
		Email:            "same@example.com",
		PasswordHash:     "hash",
		Name:             "Second User",
		Role:             domain.RoleEmployee,
		VacationBalance:  25,
		EmailPreferences: domain.DefaultEmailPreferences(),
	}
	err = repo.Create(ctx, user2)
	assert.Error(t, err, "inserting a duplicate email should fail due to UNIQUE constraint")
}

// ---------------------------------------------------------------------------
// 4. GetByEmail
// ---------------------------------------------------------------------------

func TestUserGetByEmail(t *testing.T) {
	db := testutil.SetupTestDB(t)
	repo := sqlite.NewUserRepository(db)
	ctx := context.Background()

	testutil.CreateTestUser(t, repo, "usr-email-1", "bob@example.com", "Bob Builder", domain.RoleEmployee, 20)

	fetched, err := repo.GetByEmail(ctx, "bob@example.com")
	require.NoError(t, err)
	require.NotNil(t, fetched)
	assert.Equal(t, "usr-email-1", fetched.ID)
	assert.Equal(t, "bob@example.com", fetched.Email)
	assert.Equal(t, "Bob Builder", fetched.Name)
}

// ---------------------------------------------------------------------------
// 5. GetByID not found
// ---------------------------------------------------------------------------

func TestUserGetByID_NotFound(t *testing.T) {
	db := testutil.SetupTestDB(t)
	repo := sqlite.NewUserRepository(db)
	ctx := context.Background()

	fetched, err := repo.GetByID(ctx, "non-existent-id")
	assert.NoError(t, err)
	assert.Nil(t, fetched)
}

// ---------------------------------------------------------------------------
// 6. GetByEmail not found
// ---------------------------------------------------------------------------

func TestUserGetByEmail_NotFound(t *testing.T) {
	db := testutil.SetupTestDB(t)
	repo := sqlite.NewUserRepository(db)
	ctx := context.Background()

	fetched, err := repo.GetByEmail(ctx, "nobody@example.com")
	assert.NoError(t, err)
	assert.Nil(t, fetched)
}

// ---------------------------------------------------------------------------
// 7. GetAll with pagination
// ---------------------------------------------------------------------------

func TestUserGetAll_Pagination(t *testing.T) {
	db := testutil.SetupTestDB(t)
	repo := sqlite.NewUserRepository(db)
	ctx := context.Background()

	// Create 5 users
	for i := 1; i <= 5; i++ {
		testutil.CreateTestUser(t, repo,
			fmt.Sprintf("pag-user-%d", i),
			fmt.Sprintf("pag%d@example.com", i),
			fmt.Sprintf("User %d", i),
			domain.RoleEmployee,
			25,
		)
	}

	// Fetch first page (limit 2, offset 0)
	users, total, err := repo.GetAll(ctx, nil, "", 2, 0)
	require.NoError(t, err)
	assert.Equal(t, 5, total)
	assert.Len(t, users, 2)

	// Fetch second page
	users, total, err = repo.GetAll(ctx, nil, "", 2, 2)
	require.NoError(t, err)
	assert.Equal(t, 5, total)
	assert.Len(t, users, 2)

	// Fetch third page (only 1 remaining)
	users, total, err = repo.GetAll(ctx, nil, "", 2, 4)
	require.NoError(t, err)
	assert.Equal(t, 5, total)
	assert.Len(t, users, 1)

	// Beyond range
	users, total, err = repo.GetAll(ctx, nil, "", 2, 10)
	require.NoError(t, err)
	assert.Equal(t, 5, total)
	assert.Len(t, users, 0)
}

// ---------------------------------------------------------------------------
// 8. GetAll with role filter
// ---------------------------------------------------------------------------

func TestUserGetAll_RoleFilter(t *testing.T) {
	db := testutil.SetupTestDB(t)
	repo := sqlite.NewUserRepository(db)
	ctx := context.Background()

	testutil.CreateTestUser(t, repo, "rf-admin-1", "admin1@example.com", "Admin One", domain.RoleAdmin, 0)
	testutil.CreateTestUser(t, repo, "rf-admin-2", "admin2@example.com", "Admin Two", domain.RoleAdmin, 0)
	testutil.CreateTestUser(t, repo, "rf-emp-1", "emp1@example.com", "Employee One", domain.RoleEmployee, 25)
	testutil.CreateTestUser(t, repo, "rf-emp-2", "emp2@example.com", "Employee Two", domain.RoleEmployee, 25)
	testutil.CreateTestUser(t, repo, "rf-emp-3", "emp3@example.com", "Employee Three", domain.RoleEmployee, 25)

	// Filter admins
	adminRole := domain.RoleAdmin
	users, total, err := repo.GetAll(ctx, &adminRole, "", 100, 0)
	require.NoError(t, err)
	assert.Equal(t, 2, total)
	assert.Len(t, users, 2)
	for _, u := range users {
		assert.Equal(t, domain.RoleAdmin, u.Role)
	}

	// Filter employees
	empRole := domain.RoleEmployee
	users, total, err = repo.GetAll(ctx, &empRole, "", 100, 0)
	require.NoError(t, err)
	assert.Equal(t, 3, total)
	assert.Len(t, users, 3)
	for _, u := range users {
		assert.Equal(t, domain.RoleEmployee, u.Role)
	}
}

// ---------------------------------------------------------------------------
// 9. GetAll with search
// ---------------------------------------------------------------------------

func TestUserGetAll_Search(t *testing.T) {
	db := testutil.SetupTestDB(t)
	repo := sqlite.NewUserRepository(db)
	ctx := context.Background()

	testutil.CreateTestUser(t, repo, "s-1", "charlie@example.com", "Charlie Brown", domain.RoleEmployee, 25)
	testutil.CreateTestUser(t, repo, "s-2", "charlie.delta@other.com", "Delta Force", domain.RoleEmployee, 25)
	testutil.CreateTestUser(t, repo, "s-3", "echo@example.com", "Echo Chamber", domain.RoleEmployee, 25)

	// Search by name substring — "Brown" only matches one user by name
	users, total, err := repo.GetAll(ctx, nil, "Brown", 100, 0)
	require.NoError(t, err)
	assert.Equal(t, 1, total)
	assert.Len(t, users, 1)
	assert.Equal(t, "Charlie Brown", users[0].Name)

	// Search by email substring — "charlie" matches both by email (LIKE is case-insensitive in SQLite)
	users, total, err = repo.GetAll(ctx, nil, "charlie", 100, 0)
	require.NoError(t, err)
	assert.Equal(t, 2, total)
	assert.Len(t, users, 2)

	// Search that matches no one
	users, total, err = repo.GetAll(ctx, nil, "zzzzz", 100, 0)
	require.NoError(t, err)
	assert.Equal(t, 0, total)
	assert.Len(t, users, 0)
}

// ---------------------------------------------------------------------------
// 10. GetByRole
// ---------------------------------------------------------------------------

func TestUserGetByRole(t *testing.T) {
	db := testutil.SetupTestDB(t)
	repo := sqlite.NewUserRepository(db)
	ctx := context.Background()

	// Create users with names that test ordering (ASC by name)
	testutil.CreateTestUser(t, repo, "r-emp-c", "c@example.com", "Charlie", domain.RoleEmployee, 25)
	testutil.CreateTestUser(t, repo, "r-emp-a", "a@example.com", "Alice", domain.RoleEmployee, 25)
	testutil.CreateTestUser(t, repo, "r-emp-b", "b@example.com", "Bob", domain.RoleEmployee, 25)
	testutil.CreateTestUser(t, repo, "r-admin-1", "admin@example.com", "Admin User", domain.RoleAdmin, 0)

	// Get employees — should be sorted by name ASC
	employees, err := repo.GetByRole(ctx, domain.RoleEmployee)
	require.NoError(t, err)
	require.Len(t, employees, 3)
	assert.Equal(t, "Alice", employees[0].Name)
	assert.Equal(t, "Bob", employees[1].Name)
	assert.Equal(t, "Charlie", employees[2].Name)

	// Get admins
	admins, err := repo.GetByRole(ctx, domain.RoleAdmin)
	require.NoError(t, err)
	require.Len(t, admins, 1)
	assert.Equal(t, "Admin User", admins[0].Name)
}

// ---------------------------------------------------------------------------
// 11. CountByRole
// ---------------------------------------------------------------------------

func TestUserCountByRole(t *testing.T) {
	db := testutil.SetupTestDB(t)
	repo := sqlite.NewUserRepository(db)
	ctx := context.Background()

	testutil.CreateTestUser(t, repo, "cnt-a1", "a1@example.com", "Admin A", domain.RoleAdmin, 0)
	testutil.CreateTestUser(t, repo, "cnt-a2", "a2@example.com", "Admin B", domain.RoleAdmin, 0)
	testutil.CreateTestUser(t, repo, "cnt-e1", "e1@example.com", "Emp A", domain.RoleEmployee, 25)

	adminCount, err := repo.CountByRole(ctx, domain.RoleAdmin)
	require.NoError(t, err)
	assert.Equal(t, 2, adminCount)

	empCount, err := repo.CountByRole(ctx, domain.RoleEmployee)
	require.NoError(t, err)
	assert.Equal(t, 1, empCount)
}

// ---------------------------------------------------------------------------
// 12. Update
// ---------------------------------------------------------------------------

func TestUserUpdate(t *testing.T) {
	db := testutil.SetupTestDB(t)
	repo := sqlite.NewUserRepository(db)
	ctx := context.Background()

	testutil.CreateTestUser(t, repo, "upd-1", "old@example.com", "Old Name", domain.RoleEmployee, 20)

	newStartDate := "2025-06-01"
	updated := &domain.User{
		ID:              "upd-1",
		Email:           "new@example.com",
		Name:            "New Name",
		Role:            domain.RoleAdmin,
		VacationBalance: 30,
		StartDate:       &newStartDate,
		EmailPreferences: domain.EmailPreferences{
			VacationUpdates:   false,
			WeeklyDigest:      true,
			TeamNotifications: false,
		},
	}

	err := repo.Update(ctx, updated)
	require.NoError(t, err)

	fetched, err := repo.GetByID(ctx, "upd-1")
	require.NoError(t, err)
	require.NotNil(t, fetched)

	assert.Equal(t, "new@example.com", fetched.Email)
	assert.Equal(t, "New Name", fetched.Name)
	assert.Equal(t, domain.RoleAdmin, fetched.Role)
	assert.Equal(t, 30, fetched.VacationBalance)
	require.NotNil(t, fetched.StartDate)
	assert.Equal(t, "2025-06-01", *fetched.StartDate)
	assert.False(t, fetched.EmailPreferences.VacationUpdates)
	assert.True(t, fetched.EmailPreferences.WeeklyDigest)
	assert.False(t, fetched.EmailPreferences.TeamNotifications)
}

// ---------------------------------------------------------------------------
// 13. Update non-existent user
// ---------------------------------------------------------------------------

func TestUserUpdate_NotFound(t *testing.T) {
	db := testutil.SetupTestDB(t)
	repo := sqlite.NewUserRepository(db)
	ctx := context.Background()

	user := &domain.User{
		ID:               "ghost-user",
		Email:            "ghost@example.com",
		Name:             "Ghost",
		Role:             domain.RoleEmployee,
		VacationBalance:  25,
		EmailPreferences: domain.DefaultEmailPreferences(),
	}

	err := repo.Update(ctx, user)
	assert.ErrorIs(t, err, sql.ErrNoRows)
}

// ---------------------------------------------------------------------------
// 14. UpdatePassword
// ---------------------------------------------------------------------------

func TestUserUpdatePassword(t *testing.T) {
	db := testutil.SetupTestDB(t)
	repo := sqlite.NewUserRepository(db)
	ctx := context.Background()

	testutil.CreateTestUser(t, repo, "pwd-1", "pwd@example.com", "Password User", domain.RoleEmployee, 25)

	err := repo.UpdatePassword(ctx, "pwd-1", "new-hashed-password")
	require.NoError(t, err)

	fetched, err := repo.GetByID(ctx, "pwd-1")
	require.NoError(t, err)
	require.NotNil(t, fetched)
	assert.Equal(t, "new-hashed-password", fetched.PasswordHash)
}

// ---------------------------------------------------------------------------
// 15. UpdatePassword non-existent user
// ---------------------------------------------------------------------------

func TestUserUpdatePassword_NotFound(t *testing.T) {
	db := testutil.SetupTestDB(t)
	repo := sqlite.NewUserRepository(db)
	ctx := context.Background()

	err := repo.UpdatePassword(ctx, "no-such-id", "new-hash")
	assert.ErrorIs(t, err, sql.ErrNoRows)
}

// ---------------------------------------------------------------------------
// 16. UpdateEmailPreferences
// ---------------------------------------------------------------------------

func TestUserUpdateEmailPreferences(t *testing.T) {
	db := testutil.SetupTestDB(t)
	repo := sqlite.NewUserRepository(db)
	ctx := context.Background()

	testutil.CreateTestUser(t, repo, "prefs-1", "prefs@example.com", "Prefs User", domain.RoleEmployee, 25)

	// Verify defaults were set by CreateTestUser
	fetched, err := repo.GetByID(ctx, "prefs-1")
	require.NoError(t, err)
	assert.True(t, fetched.EmailPreferences.VacationUpdates)
	assert.False(t, fetched.EmailPreferences.WeeklyDigest)
	assert.True(t, fetched.EmailPreferences.TeamNotifications)

	// Update to all opposite values
	newPrefs := domain.EmailPreferences{
		VacationUpdates:   false,
		WeeklyDigest:      true,
		TeamNotifications: false,
	}
	err = repo.UpdateEmailPreferences(ctx, "prefs-1", newPrefs)
	require.NoError(t, err)

	fetched, err = repo.GetByID(ctx, "prefs-1")
	require.NoError(t, err)
	require.NotNil(t, fetched)
	assert.False(t, fetched.EmailPreferences.VacationUpdates)
	assert.True(t, fetched.EmailPreferences.WeeklyDigest)
	assert.False(t, fetched.EmailPreferences.TeamNotifications)
}

func TestUserUpdateEmailPreferences_NotFound(t *testing.T) {
	db := testutil.SetupTestDB(t)
	repo := sqlite.NewUserRepository(db)
	ctx := context.Background()

	err := repo.UpdateEmailPreferences(ctx, "no-such-id", domain.DefaultEmailPreferences())
	assert.ErrorIs(t, err, sql.ErrNoRows)
}

// ---------------------------------------------------------------------------
// 17. UpdateVacationBalance
// ---------------------------------------------------------------------------

func TestUserUpdateVacationBalance(t *testing.T) {
	db := testutil.SetupTestDB(t)
	repo := sqlite.NewUserRepository(db)
	ctx := context.Background()

	testutil.CreateTestUser(t, repo, "bal-1", "bal@example.com", "Balance User", domain.RoleEmployee, 25)

	err := repo.UpdateVacationBalance(ctx, "bal-1", 10)
	require.NoError(t, err)

	fetched, err := repo.GetByID(ctx, "bal-1")
	require.NoError(t, err)
	require.NotNil(t, fetched)
	assert.Equal(t, 10, fetched.VacationBalance)
}

func TestUserUpdateVacationBalance_NotFound(t *testing.T) {
	db := testutil.SetupTestDB(t)
	repo := sqlite.NewUserRepository(db)
	ctx := context.Background()

	err := repo.UpdateVacationBalance(ctx, "no-such-id", 5)
	assert.ErrorIs(t, err, sql.ErrNoRows)
}

// ---------------------------------------------------------------------------
// 18. UpdateVacationBalanceTx
// ---------------------------------------------------------------------------

func TestUserUpdateVacationBalanceTx(t *testing.T) {
	db := testutil.SetupTestDB(t)
	repo := sqlite.NewUserRepository(db)
	ctx := context.Background()

	testutil.CreateTestUser(t, repo, "tx-1", "tx@example.com", "Tx User", domain.RoleEmployee, 25)

	err := db.Transaction(func(tx *sql.Tx) error {
		return repo.UpdateVacationBalanceTx(ctx, tx, "tx-1", 15)
	})
	require.NoError(t, err)

	fetched, err := repo.GetByID(ctx, "tx-1")
	require.NoError(t, err)
	require.NotNil(t, fetched)
	assert.Equal(t, 15, fetched.VacationBalance)
}

func TestUserUpdateVacationBalanceTx_NotFound(t *testing.T) {
	db := testutil.SetupTestDB(t)
	repo := sqlite.NewUserRepository(db)
	ctx := context.Background()

	err := db.Transaction(func(tx *sql.Tx) error {
		return repo.UpdateVacationBalanceTx(ctx, tx, "no-such-id", 5)
	})
	assert.ErrorIs(t, err, sql.ErrNoRows)
}

func TestUserUpdateVacationBalanceTx_RollbackOnError(t *testing.T) {
	db := testutil.SetupTestDB(t)
	repo := sqlite.NewUserRepository(db)
	ctx := context.Background()

	testutil.CreateTestUser(t, repo, "tx-rb-1", "txrb@example.com", "Tx Rollback User", domain.RoleEmployee, 25)

	// Transaction that updates balance but then returns an error — should rollback
	err := db.Transaction(func(tx *sql.Tx) error {
		if err := repo.UpdateVacationBalanceTx(ctx, tx, "tx-rb-1", 5); err != nil {
			return err
		}
		return fmt.Errorf("simulated error after update")
	})
	assert.Error(t, err)
	assert.Contains(t, err.Error(), "simulated error")

	// Balance should remain at original value due to rollback
	fetched, err := repo.GetByID(ctx, "tx-rb-1")
	require.NoError(t, err)
	require.NotNil(t, fetched)
	assert.Equal(t, 25, fetched.VacationBalance)
}

// ---------------------------------------------------------------------------
// 19. Delete
// ---------------------------------------------------------------------------

func TestUserDelete(t *testing.T) {
	db := testutil.SetupTestDB(t)
	repo := sqlite.NewUserRepository(db)
	ctx := context.Background()

	testutil.CreateTestUser(t, repo, "del-1", "del@example.com", "Delete Me", domain.RoleEmployee, 25)

	err := repo.Delete(ctx, "del-1")
	require.NoError(t, err)

	fetched, err := repo.GetByID(ctx, "del-1")
	assert.NoError(t, err)
	assert.Nil(t, fetched, "deleted user should not be found")
}

// ---------------------------------------------------------------------------
// 20. Delete non-existent user
// ---------------------------------------------------------------------------

func TestUserDelete_NotFound(t *testing.T) {
	db := testutil.SetupTestDB(t)
	repo := sqlite.NewUserRepository(db)
	ctx := context.Background()

	err := repo.Delete(ctx, "non-existent-id")
	assert.ErrorIs(t, err, sql.ErrNoRows)
}

// ---------------------------------------------------------------------------
// 21. EmailExists
// ---------------------------------------------------------------------------

func TestUserEmailExists(t *testing.T) {
	db := testutil.SetupTestDB(t)
	repo := sqlite.NewUserRepository(db)
	ctx := context.Background()

	testutil.CreateTestUser(t, repo, "ee-1", "exists@example.com", "Existing User", domain.RoleEmployee, 25)

	exists, err := repo.EmailExists(ctx, "exists@example.com")
	require.NoError(t, err)
	assert.True(t, exists)

	exists, err = repo.EmailExists(ctx, "noone@example.com")
	require.NoError(t, err)
	assert.False(t, exists)
}

// ---------------------------------------------------------------------------
// 22. EmailExistsExcluding
// ---------------------------------------------------------------------------

func TestUserEmailExistsExcluding(t *testing.T) {
	db := testutil.SetupTestDB(t)
	repo := sqlite.NewUserRepository(db)
	ctx := context.Background()

	testutil.CreateTestUser(t, repo, "eex-1", "user1@example.com", "User One", domain.RoleEmployee, 25)
	testutil.CreateTestUser(t, repo, "eex-2", "user2@example.com", "User Two", domain.RoleEmployee, 25)

	// user2's email exists, excluding user1 -> true (another user has it)
	exists, err := repo.EmailExistsExcluding(ctx, "user2@example.com", "eex-1")
	require.NoError(t, err)
	assert.True(t, exists)

	// user2's email exists, excluding user2 -> false (it is their own email)
	exists, err = repo.EmailExistsExcluding(ctx, "user2@example.com", "eex-2")
	require.NoError(t, err)
	assert.False(t, exists)

	// Non-existent email, excluding user1 -> false
	exists, err = repo.EmailExistsExcluding(ctx, "nobody@example.com", "eex-1")
	require.NoError(t, err)
	assert.False(t, exists)
}

// ---------------------------------------------------------------------------
// 23. GetNewsletterRecipients
// ---------------------------------------------------------------------------

func TestUserGetNewsletterRecipients(t *testing.T) {
	db := testutil.SetupTestDB(t)
	repo := sqlite.NewUserRepository(db)
	ctx := context.Background()

	// Create users with default preferences (weeklyDigest=false)
	testutil.CreateTestUser(t, repo, "nl-1", "nl1@example.com", "No Digest", domain.RoleEmployee, 25)
	testutil.CreateTestUser(t, repo, "nl-2", "nl2@example.com", "No Digest Either", domain.RoleEmployee, 25)

	// Create users with weeklyDigest=true by creating then updating preferences
	testutil.CreateTestUser(t, repo, "nl-3", "nl3@example.com", "Digest Alice", domain.RoleEmployee, 25)
	err := repo.UpdateEmailPreferences(ctx, "nl-3", domain.EmailPreferences{
		VacationUpdates:   true,
		WeeklyDigest:      true,
		TeamNotifications: true,
	})
	require.NoError(t, err)

	testutil.CreateTestUser(t, repo, "nl-4", "nl4@example.com", "Digest Bob", domain.RoleAdmin, 0)
	err = repo.UpdateEmailPreferences(ctx, "nl-4", domain.EmailPreferences{
		VacationUpdates:   true,
		WeeklyDigest:      true,
		TeamNotifications: true,
	})
	require.NoError(t, err)

	recipients, err := repo.GetNewsletterRecipients(ctx)
	require.NoError(t, err)
	require.Len(t, recipients, 2)

	// Ordered by name ASC: "Digest Alice" before "Digest Bob"
	assert.Equal(t, "Digest Alice", recipients[0].Name)
	assert.Equal(t, "Digest Bob", recipients[1].Name)
}

func TestUserGetNewsletterRecipients_NoneOptedIn(t *testing.T) {
	db := testutil.SetupTestDB(t)
	repo := sqlite.NewUserRepository(db)
	ctx := context.Background()

	// All users have default preferences (weeklyDigest=false)
	testutil.CreateTestUser(t, repo, "nl-none-1", "nn1@example.com", "User A", domain.RoleEmployee, 25)
	testutil.CreateTestUser(t, repo, "nl-none-2", "nn2@example.com", "User B", domain.RoleEmployee, 25)

	recipients, err := repo.GetNewsletterRecipients(ctx)
	require.NoError(t, err)
	assert.Empty(t, recipients)
}

// ---------------------------------------------------------------------------
// 24. GetLowBalanceUsers
// ---------------------------------------------------------------------------

func TestUserGetLowBalanceUsers(t *testing.T) {
	db := testutil.SetupTestDB(t)
	repo := sqlite.NewUserRepository(db)
	ctx := context.Background()

	// Employees with various balances
	testutil.CreateTestUser(t, repo, "lb-1", "lb1@example.com", "Low One", domain.RoleEmployee, 3)
	testutil.CreateTestUser(t, repo, "lb-2", "lb2@example.com", "Low Two", domain.RoleEmployee, 5)
	testutil.CreateTestUser(t, repo, "lb-3", "lb3@example.com", "High Balance", domain.RoleEmployee, 20)
	testutil.CreateTestUser(t, repo, "lb-4", "lb4@example.com", "Zero Balance", domain.RoleEmployee, 0)

	// Admin with low balance — should NOT be returned
	testutil.CreateTestUser(t, repo, "lb-admin", "lba@example.com", "Admin Low", domain.RoleAdmin, 2)

	users, err := repo.GetLowBalanceUsers(ctx, 5)
	require.NoError(t, err)
	require.Len(t, users, 3) // 0, 3, 5 — all <= 5

	// Ordered by vacation_balance ASC
	assert.Equal(t, 0, users[0].VacationBalance)
	assert.Equal(t, 3, users[1].VacationBalance)
	assert.Equal(t, 5, users[2].VacationBalance)

	// Verify no admin in the results
	for _, u := range users {
		assert.Equal(t, domain.RoleEmployee, u.Role)
	}
}

func TestUserGetLowBalanceUsers_NoneBelow(t *testing.T) {
	db := testutil.SetupTestDB(t)
	repo := sqlite.NewUserRepository(db)
	ctx := context.Background()

	testutil.CreateTestUser(t, repo, "lb-high-1", "lbh1@example.com", "Rich User", domain.RoleEmployee, 25)

	users, err := repo.GetLowBalanceUsers(ctx, 5)
	require.NoError(t, err)
	assert.Empty(t, users)
}

// ---------------------------------------------------------------------------
// 25. UpdateAllBalances
// ---------------------------------------------------------------------------

func TestUserUpdateAllBalances(t *testing.T) {
	db := testutil.SetupTestDB(t)
	repo := sqlite.NewUserRepository(db)
	ctx := context.Background()

	// Create mix of employees and admins
	testutil.CreateTestUser(t, repo, "ub-emp-1", "ub1@example.com", "Emp One", domain.RoleEmployee, 10)
	testutil.CreateTestUser(t, repo, "ub-emp-2", "ub2@example.com", "Emp Two", domain.RoleEmployee, 5)
	testutil.CreateTestUser(t, repo, "ub-emp-3", "ub3@example.com", "Emp Three", domain.RoleEmployee, 0)
	testutil.CreateTestUser(t, repo, "ub-admin-1", "ub-admin@example.com", "Admin One", domain.RoleAdmin, 99)

	affected, err := repo.UpdateAllBalances(ctx, 25)
	require.NoError(t, err)
	assert.Equal(t, int64(3), affected, "only 3 employees should be affected")

	// Verify employee balances reset
	emp1, err := repo.GetByID(ctx, "ub-emp-1")
	require.NoError(t, err)
	assert.Equal(t, 25, emp1.VacationBalance)

	emp2, err := repo.GetByID(ctx, "ub-emp-2")
	require.NoError(t, err)
	assert.Equal(t, 25, emp2.VacationBalance)

	emp3, err := repo.GetByID(ctx, "ub-emp-3")
	require.NoError(t, err)
	assert.Equal(t, 25, emp3.VacationBalance)

	// Verify admin balance unchanged
	admin, err := repo.GetByID(ctx, "ub-admin-1")
	require.NoError(t, err)
	assert.Equal(t, 99, admin.VacationBalance, "admin balance should not be changed")
}

func TestUserUpdateAllBalances_NoEmployees(t *testing.T) {
	db := testutil.SetupTestDB(t)
	repo := sqlite.NewUserRepository(db)
	ctx := context.Background()

	// Only admins in the database
	testutil.CreateTestUser(t, repo, "ub-only-admin", "only-admin@example.com", "Admin Only", domain.RoleAdmin, 50)

	affected, err := repo.UpdateAllBalances(ctx, 25)
	require.NoError(t, err)
	assert.Equal(t, int64(0), affected)
}

// ---------------------------------------------------------------------------
// Additional edge cases
// ---------------------------------------------------------------------------

func TestUserCreate_NilStartDate(t *testing.T) {
	db := testutil.SetupTestDB(t)
	repo := sqlite.NewUserRepository(db)
	ctx := context.Background()

	user := &domain.User{
		ID:               "nil-sd-1",
		Email:            "nosd@example.com",
		PasswordHash:     "hash",
		Name:             "No Start Date",
		Role:             domain.RoleEmployee,
		VacationBalance:  25,
		StartDate:        nil,
		EmailPreferences: domain.DefaultEmailPreferences(),
	}

	err := repo.Create(ctx, user)
	require.NoError(t, err)

	fetched, err := repo.GetByID(ctx, "nil-sd-1")
	require.NoError(t, err)
	require.NotNil(t, fetched)
	assert.Nil(t, fetched.StartDate)
}

func TestUserGetAll_CombinedRoleAndSearch(t *testing.T) {
	db := testutil.SetupTestDB(t)
	repo := sqlite.NewUserRepository(db)
	ctx := context.Background()

	testutil.CreateTestUser(t, repo, "cs-1", "alice.admin@example.com", "Alice Admin", domain.RoleAdmin, 0)
	testutil.CreateTestUser(t, repo, "cs-2", "alice.emp@example.com", "Alice Employee", domain.RoleEmployee, 25)
	testutil.CreateTestUser(t, repo, "cs-3", "bob.emp@example.com", "Bob Employee", domain.RoleEmployee, 25)

	// Search for "Alice" among employees only
	empRole := domain.RoleEmployee
	users, total, err := repo.GetAll(ctx, &empRole, "Alice", 100, 0)
	require.NoError(t, err)
	assert.Equal(t, 1, total)
	require.Len(t, users, 1)
	assert.Equal(t, "Alice Employee", users[0].Name)
}

func TestUserGetAll_OrderByCreatedAtDesc(t *testing.T) {
	db := testutil.SetupTestDB(t)
	repo := sqlite.NewUserRepository(db)
	ctx := context.Background()

	// Create users sequentially — in SQLite with datetime('now') they may share the
	// same second, so we verify the general query succeeds and returns all users.
	testutil.CreateTestUser(t, repo, "ord-1", "ord1@example.com", "First Created", domain.RoleEmployee, 25)
	testutil.CreateTestUser(t, repo, "ord-2", "ord2@example.com", "Second Created", domain.RoleEmployee, 25)
	testutil.CreateTestUser(t, repo, "ord-3", "ord3@example.com", "Third Created", domain.RoleEmployee, 25)

	users, total, err := repo.GetAll(ctx, nil, "", 100, 0)
	require.NoError(t, err)
	assert.Equal(t, 3, total)
	assert.Len(t, users, 3)
}
